[package]
name = "youmubot-osu"
version = "0.1.0"
authors = ["Natsu Kagami <natsukagami@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10"
chrono = "0.4"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
bitflags = "1"
lazy_static = "1"
regex = "1"
oppai-rs = "0.2"
dashmap = "4"
bincode = "1"

youmubot-db = { path = "../youmubot-db" }
youmubot-db-sql = { path = "../youmubot-db-sql" }
youmubot-prelude = { path = "../youmubot-prelude" }

[dev-dependencies]
serde_json = "1"
